### ISSUE TITLE
Add namespace to placementRef in DRPC for ODF Console Compatibility(Optional)

### ISSUE THREAD

**Issue by GowthamShanmugam** [RamenDR/ocm-ramen-samples#65]
#### **Description**  
Currently, the `DRPlacementControl` (DRPC) YAML in `ocm-ramen-samples` does not include the `namespace` field under `placementRef`.. However, for OpenShift, the ODF Console expects the `placementRef` to include the **name, kind, and namespace** to properly fetch and display DRPC details.  

 this is **not an immediate requirement** but a **good-to-have improvement** for future compatibility.  

#### **Priority:** Low (Optional Fix)  
- This issue is being created as a **reminder** for potential future enhancement.  

#### **Possible Fix**  
To make this compatible with the OpenShift console, `placementRef` should include `namespace`, but since DRPC can be deployed in any namespace, we need a way to dynamically inject the namespace when applying the YAML.  

Example of the required change:  
```yaml
placementRef:
  kind: Placement
  name: placement
  namespace: NAMESPACE  # Needs to be set based on placement namespace
```
---
